contexts:
  local:
    base_url: http://localhost:3000
    # todo: allow for non-string characters
    pagination_limit: "10"
requests:
  get-posts:
    tags: [get]
    description: a simple get
    url: "${base_url}/posts"
    query_parameters:
      _limit: "${pagination_limit}"

  get-user-from-first-post:
    tags: [get]
    description: get the info for the first user from the call to get-posts
    url: "${base_url}/users/${response.get-posts.0.userId}"

  new-post:
    tags: [post]
    description: make a new post
    url: "${base_url}/posts"
    method: "POST"
    headers:
      content-type: application/json
    body:
      type: raw
      from:
        type: text
        data: |
          {
            "userId": 1,
            "title": "test post",
            "body": "This is a test post to the json server."
          }

  get-new-post:
    tags: [get]
    description: get the post from new-post
    url: "${base_url}/posts/${response.new-post.id}"
